version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres   # Esse valor deve ser o nome do serviço do banco de dados
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cbc
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cbc
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
